language: android

env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
android:
  components:
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
script:
  - ./gradlew test --stacktrace
  - ./gradlew assembleDebug assembleRelease --stacktrace
